[tool.poetry]
name = "kagi"
version = "0.1.0"
description = "Django app for WebAuthn and TOTP-based multi-factor authentication"
authors = ["Justin Mayer <entroP@gmail.com>", "RÃ©my Hubscher <hubscher.remy@gmail.com>"]
license = "BSD-2-Clause"
readme = "README.rst"
keywords = ["Django", "WebAuthn", "authentication", "MFA", "2FA"]

[tool.poetry.dependencies]
Django = "^2.2"
python = "^3.6"
qrcode = "^6.1"
webauthn = "^0.4.5"

[tool.poetry.dev-dependencies]
black = {version = "^19.3b0",allows-prereleases = true}
django-extensions = "^2.2"
flake8 = "^3.7"
flake8-black = "^0.1.0"
isort = "^4.3"
pyOpenSSL = "^19.0"
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-django = "^3.5"
pytest-emoji = "^0.2.0"
pytest-pythonpath = "^0.7.3"
pytest-sugar = "^0.9.2"
Werkzeug = "^0.15.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
